# Generated by Django 4.1.3 on 2022-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20211025_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="https://asset.cloudinary.com/allan-gerald-sserwanga/9f91b9276ebf2f4eff14e33693694d8f",
                upload_to="avatars",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                default="https://asset.cloudinary.com/allan-gerald-sserwanga/23185c07c102f02509e0e6131d1bbc60",
                upload_to="avatars",
            ),
        ),
    ]
