# Generated by Django 4.1.3 on 2022-11-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_avatar_alter_user_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="profile_yzijzd.jpg", upload_to="avatars"),
        ),
        migrations.AlterField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(default="cover_iqsrdp.jpg", upload_to="avatars"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
